[project]
name = "videoleech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyside6>=6.10.1",
    "quickjs>=1.19.4",
    "yt-dlp>=2025.10.14",
]
